/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0uQ3MvStDxw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import SimpleMenu from '@/components/menus/simpleMenu';
import { CustomerProfile } from '@/components/customers/customerProfile';

export default async function CustomerProfilePage({
  params
}: {
  params: { email: string };
}) {
  const email = params.email.split('%40').join('@');
  return (
    <div className="flex h-full flex-col">
      <SimpleMenu />
      <CustomerProfile email={email} />
    </div>
  );
}
