/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0uQ3MvStDxw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { fetchCustomer } from 'actions/customer';
import { CustomerProfile } from '@/components/customers/customerProfile';
import { Suspense } from 'react';

export default async function CustomerProfilePage({
  params
}: {
  params: { email: string };
}) {
  const email = params.email.split('%40').join('@');
  return (
    <div className="container mx-auto px-4 py-8 md:px-6 md:py-12">
      <Suspense fallback={<></>}>
        <CustomerProfile email={email} />
      </Suspense>
    </div>
  );
}
