/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/shOCCSdmJAC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { AlertDialogTrigger, AlertDialogTitle, AlertDialogHeader, AlertDialogFooter, AlertDialogContent, AlertDialog } from "@/components/ui/alert"

export function badRequestDialog() {
  return (
    <AlertDialog defaultOpen open>
      <AlertDialogTrigger asChild>
        <Button variant="destructive">Submit Form</Button>
      </AlertDialogTrigger>
      <AlertDialogContent className="sm:max-w-[420px]">
        <AlertDialogHeader>
          <AlertDialogTitle>Error</AlertDialogTitle>
        </AlertDialogHeader>
        <div>
          <p>There was an issue submitting your form. Please check your inputs and try again.</p>
        </div>
        <AlertDialogFooter>
          <div>
            <Button variant="outline">Close</Button>
          </div>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}
