/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0uQ3MvStDxw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import CustomerInfo from './customers/customerProfileSections/customerInfo';
import CustomerPetInfo from './customers/customerProfileSections/petInfo';
import CustomerPetAppointments from './customers/customerProfileSections/customerPetAppointments';
import { Customers } from '@/lib/schema';

export function CustomerProfile({ customer }: { customer: Customers }) {
  return (
    <div className="container mx-auto px-4 py-8 md:px-6 md:py-12">
      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
        <CustomerInfo customer={customer} />
        <CustomerPetInfo />
        <CustomerPetAppointments />
      </div>
    </div>
  );
}
