/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/v6H7EBda3MH
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  DialogTrigger,
  DialogTitle,
  DialogDescription,
  DialogHeader,
  DialogFooter,
  DialogContent,
  Dialog
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export default function ErrorDialog({
  errors,
  open
}: {
  errors: string | string[];
  open: boolean;
}) {
  return (
    <Dialog open={open}>
      <DialogTrigger asChild>
        <button className="hidden" />
      </DialogTrigger>
      <DialogContent className="sm:max-w-[400px]">
        <DialogHeader>
          <DialogTitle>Oops, something went wrong</DialogTitle>
          <DialogDescription>
            We encountered an error while processing your request.
          </DialogDescription>
          <DialogDescription>
            {Array.isArray(errors)
              ? errors.map((error) => error + '\n')
              : errors}
          </DialogDescription>
        </DialogHeader>
        <DialogFooter className="justify-between">
          <Button variant="outline">Close</Button>
          <Link className="inline-flex" href="#">
            Help Center
          </Link>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
