/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FpgQGPXOc9e
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import PetsOnSiteCard from './petsOnSite/petsOnSiteCard';
import FinancialsCard from './financials/financialsCard';

export default function PetDashboard() {
  return (
    <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
      <div className="grid md:grid-cols-2 gap-6">
        <PetsOnSiteCard />
        <FinancialsCard />
      </div>
    </main>
  );
}
