/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FpgQGPXOc9e
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { Input } from '@/components/ui/input';
import { CardTitle, CardHeader, CardContent, Card } from '@/components/ui/card';
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select
} from '@/components/ui/select';
import { PawPrintIcon } from './icons';

export function PuppyDashboard() {
  return (
    <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
      <div className="grid md:grid-cols-2 gap-6">
        <Card className="flex flex-col h-full">
          <CardHeader>
            <CardTitle>Animals On Site</CardTitle>
            <div className="flex items-center gap-2">
              <Select>
                <SelectTrigger className="w-[150px]">
                  <SelectValue placeholder="Filter by" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="name">Name</SelectItem>
                  <SelectItem value="type">Type</SelectItem>
                  <SelectItem value="service">Service</SelectItem>
                </SelectContent>
              </Select>
              <Input
                className="w-full bg-white shadow-none appearance-none pl-4 md:w-2/3 lg:w-1/3 dark:bg-gray-950"
                placeholder="Search"
                type="search"
              />
            </div>
          </CardHeader>
          <CardContent className="flex-1 grid gap-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <PawPrintIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                <div>
                  <div className="font-medium">Buddy</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">
                    Dog
                  </div>
                </div>
              </div>
              <div className="text-sm font-medium">Grooming</div>
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <PawPrintIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                <div>
                  <div className="font-medium">Whiskers</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">
                    Cat
                  </div>
                </div>
              </div>
              <div className="text-sm font-medium">Boarding</div>
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <PawPrintIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                <div>
                  <div className="font-medium">Daisy</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">
                    Rabbit
                  </div>
                </div>
              </div>
              <div className="text-sm font-medium">Daycare</div>
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <PawPrintIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                <div>
                  <div className="font-medium">Buddy</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">
                    Dog
                  </div>
                </div>
              </div>
              <div className="text-sm font-medium">Grooming</div>
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <PawPrintIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                <div>
                  <div className="font-medium">Whiskers</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">
                    Cat
                  </div>
                </div>
              </div>
              <div className="text-sm font-medium">Boarding</div>
            </div>
          </CardContent>
        </Card>
        <Card className="flex flex-col h-full">
          <CardHeader>
            <CardTitle>Daily Financials</CardTitle>
          </CardHeader>
          <CardContent className="flex-1 grid gap-4">
            <div className="flex items-center justify-between">
              <div>Total Revenue</div>
              <div className="text-2xl font-bold">$1,250</div>
            </div>
            <div className="flex items-center justify-between">
              <div>Appointments</div>
              <div className="text-sm font-medium">15</div>
            </div>
            <div className="flex items-center justify-between">
              <div>Average Ticket</div>
              <div className="text-sm font-medium">$83</div>
            </div>
            <div className="flex items-center justify-between">
              <div>Total Revenue</div>
              <div className="text-2xl font-bold">$1,250</div>
            </div>
            <div className="flex items-center justify-between">
              <div>Appointments</div>
              <div className="text-sm font-medium">15</div>
            </div>
            <div className="flex items-center justify-between">
              <div>Average Ticket</div>
              <div className="text-sm font-medium">$83</div>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
