/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/v9kbM6NxAM5
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Button } from '@/components/ui/button';
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table
} from '@/components/ui/table';
import { AvatarImage, AvatarFallback, Avatar } from '@/components/ui/avatar';
import UpdatePetServiceForm from './forms/UpdatePetService';

export default function PetsOnSite() {
  return (
    <div className="flex flex-col h-full">
      <main className="flex-1 p-6">
        <div className="flex justify-between items-center mb-6"></div>
        <div className="border rounded-lg overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Pet</TableHead>
                <TableHead>Service</TableHead>
                <TableHead>Departure</TableHead>
                <TableHead>Details</TableHead>
                <TableHead />
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>
                  <div className="flex items-center gap-3">
                    <Avatar className="w-10 h-10">
                      <AvatarImage alt="Buddy" src="/placeholder-avatar.jpg" />
                      <AvatarFallback>B</AvatarFallback>
                    </Avatar>
                    <div>
                      <div className="font-medium">Buddy</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        Golden Retriever
                      </div>
                    </div>
                  </div>
                </TableCell>
                <TableCell>Grooming</TableCell>
                <TableCell>
                  <div>May 22, 2023</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">
                    10:00 AM
                  </div>
                </TableCell>
                <TableCell>
                  <div>Nail trim, bath</div>
                </TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <UpdatePetServiceForm />
                    <Button className="ml-2">Check Out</Button>
                  </div>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </main>
    </div>
  );
}
