/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yrzMzw5GYT6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table
} from '@/components/ui/table';

export default function Loading() {
  return (
    <div className="flex flex-col h-full animate-pulse">
      <header className="bg-gray-200 dark:bg-gray-700 px-6 py-4 border-b border-gray-300 dark:border-gray-600">
        <div className="h-6 bg-gray-300 dark:bg-gray-600 rounded w-48" />
      </header>
      <main className="flex-1 p-6">
        <div className="flex justify-between items-center mb-6">
          <div>
            <div className="h-10 bg-gray-300 dark:bg-gray-600 rounded w-32" />
          </div>
          <div className="flex items-center gap-2">
            <div className="h-10 bg-gray-300 dark:bg-gray-600 rounded w-48" />
            <div className="h-10 bg-gray-300 dark:bg-gray-600 rounded w-10" />
          </div>
        </div>
        <div className="border rounded-lg overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>
                  <div className="h-6 bg-gray-300 dark:bg-gray-600 rounded w-20" />
                </TableHead>
                <TableHead>
                  <div className="h-6 bg-gray-300 dark:bg-gray-600 rounded w-24" />
                </TableHead>
                <TableHead>
                  <div className="h-6 bg-gray-300 dark:bg-gray-600 rounded w-20" />
                </TableHead>
                <TableHead>
                  <div className="h-6 bg-gray-300 dark:bg-gray-600 rounded w-24" />
                </TableHead>
                <TableHead>
                  <div className="h-6 bg-gray-300 dark:bg-gray-600 rounded w-10" />
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-gray-300 dark:bg-gray-600 rounded-full" />
                    <div>
                      <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-24" />
                      <div className="h-3 bg-gray-300 dark:bg-gray-600 rounded w-16 mt-1" />
                    </div>
                  </div>
                </TableCell>
                <TableCell>
                  <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-20" />
                </TableCell>
                <TableCell>
                  <div>
                    <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-16" />
                    <div className="h-3 bg-gray-300 dark:bg-gray-600 rounded w-12 mt-1" />
                  </div>
                </TableCell>
                <TableCell>
                  <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-24" />
                </TableCell>
                <TableCell>
                  <div className="h-10 bg-gray-300 dark:bg-gray-600 rounded w-10" />
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-gray-300 dark:bg-gray-600 rounded-full" />
                    <div>
                      <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-24" />
                      <div className="h-3 bg-gray-300 dark:bg-gray-600 rounded w-16 mt-1" />
                    </div>
                  </div>
                </TableCell>
                <TableCell>
                  <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-20" />
                </TableCell>
                <TableCell>
                  <div>
                    <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-16" />
                    <div className="h-3 bg-gray-300 dark:bg-gray-600 rounded w-12 mt-1" />
                  </div>
                </TableCell>
                <TableCell>
                  <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-24" />
                </TableCell>
                <TableCell>
                  <div className="h-10 bg-gray-300 dark:bg-gray-600 rounded w-10" />
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-gray-300 dark:bg-gray-600 rounded-full" />
                    <div>
                      <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-24" />
                      <div className="h-3 bg-gray-300 dark:bg-gray-600 rounded w-16 mt-1" />
                    </div>
                  </div>
                </TableCell>
                <TableCell>
                  <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-20" />
                </TableCell>
                <TableCell>
                  <div>
                    <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-16" />
                    <div className="h-3 bg-gray-300 dark:bg-gray-600 rounded w-12 mt-1" />
                  </div>
                </TableCell>
                <TableCell>
                  <div className="h-4 bg-gray-300 dark:bg-gray-600 rounded w-24" />
                </TableCell>
                <TableCell>
                  <div className="h-10 bg-gray-300 dark:bg-gray-600 rounded w-10" />
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </main>
    </div>
  );
}
